#ifndef ERRORS_H

#define ERRORS_H

#include <errno.h>

typedef enum Errors {
    NULL_ARGUMENT,
    
    ALREADY_ALLOCATED,
    ALREADY_DEALLOCATED,
    FAILED_TO_ALLOCATE,
    FAILED_TO_COPY,

    TYPE_IS_WRONG,
    NON_DATA_TRUNCATED,
    CRC_VALIDATION_FAILED,
    PAYLOAD_VALIDATION_FAILED,

    INVALID_LENGTH,

    REGEX_COMPILATION_FAILED,

    CLI_O_VALUE_MISSING,
    CLI_UNKNOWN_OPTION,
    CLI_IP_MISSING,
    CLI_PORT_MISSING,
    CLI_TOO_MANY_ARGUMENTS,
    CLI_FORMAT_VALIDATION_FAILED,
    CLI_IP_INVALID,
    CLI_MAX_INVALID,
    CLI_PORT_INVALID,

    STR2INT_INCONVERTIBLE,
    STR2INT_OVERFLOW,
    STR2INT_UNDERFLOW,
    STR2INT_NOT_END,

    FAILED_TO_INIT_MUTEX,
    FAILED_TO_INIT_COND,

    FAILED_TO_RESIZE,
    WRONG_SIZE,

    UNKNOWN

} errors_t;

#endif